feat:トップページ、登録ページの作成
yuta10200831/7-5.docker-templete pull request #5
Opened 2023-09-07 12:32 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/5-6e2c34f4fdf445cbb209f263b504acda

## 作業詳細
・トップページの作成
・まとめ登録ページの作成
・登録の際に不備があったらエラーメッセージの表示
・トップページにデータを表示

## 備考
編集ボタン、削除ボタンが表示されているかの確認までしたかったのでまとめてのプルリクになります。
宜しくお願い致します。

2023-09-07 22:11 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-09-07 22:11 UTC, KatsuyaTanaka95 commented on src/public/store.php
> +}
ここをガード節にしましょう！😊
慣れるまで（ある程度ガード節で書くことを忘れないようになるまで）は、テスト観点に「ガード節にする」と入れておきましょう！！
また同じミスをしたなとなった際には、「次に同じミスをしないように工夫をする」と良いと思います！！😊

2023-09-08 07:08 UTC, yuta10200831 commented
修正しました。
ご確認宜しくお願い致します！

助言ありがとうございます！
今後、ガード節に関してはテスト観点に記載ミス削減に繋げます。

2023-09-10 21:33 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-09-11 05:49 UTC, merged